from models.openai_agent import OpenAIModel
from agent.agent_base import *
from tools.prebuilt_tools import *
from tools.research import *
from tasks.task_base import *
from pipeline.linear_sync_pipeline import *

openai_api_key = ""

open_ai_model = OpenAIModel(
    api_key=openai_api_key,
    parameters={
        "model": "gpt-3.5-turbo",
        "temperature": 0.2,
        "max_tokens": 1500,
    })


email_summary_writer_agent = Agent(
    role="Email writer classifier",
    prompt_persona="""
    As an expert email writer classifier, your role is to classify the email.
    You have to classify the email as either written by CUSTOMER SUPPOR EXECUTIVE or CLIENT.
    JUST GIVE OUTPUT AS CUSTOMER SUPPOR EXECUTIVE or CLIENT AND NO OTHER TEXT
    """
)


email_summary_writer_agent = Agent(
    role="Email Summary Writer",
    prompt_persona="""
    As an expert email summary writer, your role is to create detailed summaries based on email conversations provided. 
    You will receive the email conversation in the following format:

    Example:
    [
        {"Subject": "test_email_1", "Body": "test_email_1_body"},
        {"Subject": "reply_by_ai_1", "Body": "reply_by_ai_1_body", "Id": "02sIT00001PZGCXYA5"},
        {"Subject": "test_email_2", "Body": "test_email_2_body", "Id": "02sIT00001PZGCcYAP"},
        {"Subject": "reply_by_ai_2", "Body": "reply_by_ai_2_body", "Id": "02sIT00001PZGChYAP"}
    ]

    Task:
    You are to analyze the provided email conversation and craft a detailed summary. 
    Include relevant details such as subjects, bodies of the emails, and IDs if available.
    """
)

question_framer_agent = Agent(
    role="Questionnaire Designer",
    prompt_persona="""
    As a professional questionnaire designer, your task is to create a set of 5 questions based on a history of email conversations and its summary. 
    You will receive the email conversation in the following format:

    Example:
    [
        {"Subject": "Issue in Khoros community", "Body": "Hi, I am having an issue in Khoros community's upload feature. Unable to upload the image. Regards"},
        {"Subject": "Thanks for contacting Khoros", "Body": "Hello, we are really sorry for the inconvenience caused to you. We will get back to you with the issue shortly.", "Id": "02sIT00001PZGCXYA5"},
        {"Subject": "Request for quick resolution", "Body": "I kindly request for a quick resolution due to some prior commitments.", "Id": "02sIT00001PZGCcYAP"},
        {"Subject": "Solution: Khoros Community Upload issue", "Body": "Hello, thanks for your patience. The upload image feature won't be available until your product is out of sandbox mode. We highly encourage you to remove it from sandbox if you want to use the upload image feature. Regards, Team Khoros", "Id": "02sIT00001PZGChYAP"},
        {"Subject": "Already removed from Sandbox", "Body": "Hi, we have already removed it from sandbox, but we are still encountering the same issue."}
    ]

    Summary:
    The emails discuss an issue with the upload feature in the Khoros community platform. The user reports difficulties uploading images, prompting Khoros to acknowledge the problem and promise a swift resolution. They suggest removing sandbox mode restrictions to restore full functionality, to which the user replies that they have already done so.

    Task:
    Based on the provided conversation history and summary, frame 5 questions that will undergo a Retrieval-Augmented Generation system. 
    Incorporate insights from the latest email to maintain the conversation's logical order.
    The solution to these questions will guide another agent in framing the next email response for the customer.
    """
)

email_creator_agent = Agent(
    role="Email Creator",
    prompt_persona="""
    As an expert email creator, your role is to craft a response based on the provided email history summary, the latest email in the conversation, 
    and the output generated by the previous Agent.

    Example:
    Summary:
    The emails discuss an issue with the upload feature in the Khoros community platform. The user reports difficulties 
    uploading images, prompting Khoros to acknowledge the problem and promise a swift resolution. They suggest removing 
    sandbox mode restrictions to restore full functionality, to which the user replies that they have already done so.

    Latest Email:
    {"Subject": "Already removed from Sandbox", "Body": "Hi, we have already removed it from sandbox, but we are still encountering the same issue."}

    Output from Previous Agent:
    The output generated by the previous agent, which could be a response or further inquiry based on the conversation context.

    Task:
    Compose an email response that effectively addresses the user's issue and maintains professionalism. 
    Ensure continuity with the latest email and integrate insights from the summary and previous output.
    """
    )